### ISSUE TITLE
Working with empty files not possible

### ISSUE THREAD

**Issue by xploreraj** [xploreraj/ytools#5]
Creating new information on an empty file is leading to exceptions and not possible now. As of now, at least one module information has to be present in file, Else following problems occur:
1. file is cleared (even if some key is null, since we are converting names keyset to Treeset which throws NPE.

```
Module.getSubModuleNames()
ModulesData.getModuleNames()
```
1. 

```
May 08, 2016 2:47:17 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [controller.AjaxController] in context with path [/theFaqApp] threw exception
java.lang.ClassCastException: org.boon.core.value.CharSequenceValue cannot be cast to data.ModulesData
    at service.FAQReadWriteService.getModulesData(FAQReadWriteService.java:27)
    at controller.AjaxController.doPost(AjaxController.java:48)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
```

**Comment by xploreraj** [comment]
For an empty JSON, mapping to `ModulesData.class` leads to `ClassCastException`, that we can handle and decide to create new `Module` object. This will suffice I think, since a `Module` will have at least one `SubModule`.

**Comment by xploreraj** [comment]
```
public static ModulesData getModulesData() throws FileNotFoundException {
        ModulesData modulesData;
        try {
            modulesData = mapper.readValue(new FileInputStream(FILE_NAME),  ModulesData.class);
        }
        catch(ClassCastException e) {
            //If file is empty, then Boon throws CCE while trying to map with ModulesData.class
            modulesData = null;
        }
        return modulesData;
    }
```

Works now.
